### PR TITLE
using afero rclone backend to provide ability of mounting different kinds of service

### PR DESCRIPTION
**Pull request by chaoqing**
[rclone](https://github.com/rclone/rclone/) is a golang library which support many kinds of cloud storage. On Linux it provide the ability of FUSE mount but that require root permission.

[afero](https://github.com/spf13/afero) is another golang package with drop-in replacement ability to operating system file system. I combined those two package to do the mount inside golang context so that root permission is not needed.

Using my afero fork https://github.com/chaoqing/afero, I added the rclone ability to Cloudreve local driver so that a variety of stroage like Google Drive, S3, Dropbox, etc. can be managed by Cloudreve.

All one need to do is generating rclone configure file as https://rclone.org/commands/rclone_config_create/ showed and then add following section into Cloudreve conf.ini

```
[RClone]
Config = path/to/rclone.conf
Binds = /virtual/mount/point:rclone-section-name, /mnt/gdrive:gdrive
```

Then one can configure the local storage policy by choosing like `/mnt/gdrive/uploads` as upload folder. Everything should work like the `/mnt/gdrive` exist on local file system.

### CODE REVIEW

**Comment by HFO4** [comment]
Thanks for the PR! but I'm confused why we need to implement it in such complexity.

If you want to mount OneDrive or S3, just use existing policy support.
If you want to use rclone, I believe root permission is not a big deal.

**Comment by chaoqing** [comment]
The main reason I implemented this is because of Google drive, Dropbox and Teracloud. They all share common drawbacks, behind the GFW or very poor connectivity. In this case Cloudreve hosted out of China become sort of proxy to those services and we have video streaming feature.

The root permission on Linux may not be big problem but using os provided mount function require multiple process and separate configurations. With this fork everything is in one binary and easy to manage with docker.

**Comment by HFO4** [comment]
> The main reason I implemented this is because of Google drive, Dropbox and Teracloud. They all share common drawbacks, behind the GFW or very poor connectivity. In this case Cloudreve hosted out of China become sort of proxy to those services and we have video streaming feature.
> 
> The root permission on Linux may not be big problem but using os provided mount function require multiple process and separate configurations. With this fork everything is in one binary and easy to manage with docker.

I see...

There are several concerns and suggestions about your implementation.

* Only one bind relation is supported.
* This binding will infiltrate `util` pkg, which might be used by other modules other than uploading, as well as other `Local` policy.
* Will it break on Windows path model? For example, path like `C:\Documents`.

In my opinion, a better approach is adding a new policy type, all binding and filesystem transition will be done inside this policy's `Handler` interface. No other component in Cloudreve will be affected.

**Comment by chaoqing** [comment]
Sorry, what do you mean by "only one relation supported"? Actually it can bind different kinds of service in the same time.

Yes my first option is to implemented a separate policy but I don't have the skills on front end part. And I don't have Windows environment to test the functionality. We can disable the functionality on Windows system.

If this binding functionality is not enabled, then all filesystem operation will happen on afero OsFs, which is a widely used drop-in replacement on the os package. I believe we are safe to update utils in this circumstance.

**Pull request closed without merging**
