### PR TITLE
make zip contents seekable

### PR DESCRIPTION
**Pull request by xb2016**
Fix "seeker can't seek" error

### CODE REVIEW

**Comment by vvisionnn** [comment]
why are you want to seek the content of a zipped file? please provide more context of it, thanks

**Comment by xb2016** [comment]
> why are you want to seek the content of a zipped file? please provide more context of it, thanks

For Windows version of Cloudreve, file `codicon.b13daaad.ttf` is not seekable.

image

**Comment by HFO4** [comment]
For every incoming request for statics, we will buffering that file into memory? I don’t think it’s a long term solution….

**Comment by xb2016** [comment]
> For every incoming request for statics, we will buffering that file into memory? I don’t think it’s a long term solution….

In fact I prefer not to compress static resources if there is no other solution.

**Pull request closed without merging**
