### PR TITLE
Comply with Golang semantic import versioning

### PR DESCRIPTION
**Pull request by Loyalsoldier**

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
The design article about Golang Semantic Import Versioning: https://research.swtch.com/vgo-import

**Review by HFO4 — APPROVED** [review]

**Comment by HFO4** [comment]
Thanks!

**Comment by HFO4** [comment]
Thanks!

**Comment by Loyalsoldier** [comment]
You should also tag this commit to make it work.

**Pull request merged**
